spring:
  h2:
    console:
      path: /h2-console #进入h2 web操作界面的路径
      enabled: true #开启h2 web界面
  datasource:
    master:
#      type: com.zaxxer.hikari.HikariDataSource
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db_test
      username: root
      password: 1111
#      password: "{cipher}CBuT0hQ+CsjbByL0DYW4zw=="


#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://mecs.com:3306/tdatabase?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=false&allowMultiQueries=true&useCursorFetch=true
#      username: root
#      password: 1111
      connection-timeout: 2000
      hikari:
        maximum-pool-size: 60
      schema:
        - classpath:db/schema-h2.sql
      data:
        - classpath:db/data-h2.sql
      initialization-mode: always
      mybatis:
        mapper-locations: classpath:mapper/*.xml, classpath:config/mapper/*.xml

    slave:
#      type: com.alibaba.druid.pool.DruidDataSource
#      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.h2.Driver
#      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:h2:mem:db_test
#      url: jdbc:mysql://mecs.com:3306/tdatabase?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=false&allowMultiQueries=true&useCursorFetch=true
      username: root
      password: 1111
      connection-timeout: 2000
      hikari:
        connection-timeout: 30000
        minimum-idle: 100
        maximum-pool-size: 99
        maxLifetime: 0
        idle-timeout: 88888
      jpa:
        database: mysql
        #启动时需要初始化的建表语句
        schema: classpath:db/schema-h2.sql
        #初始化的数据
        data: classpath:db/data-h2.sql
        show-sql: true
        open-in-view: false
        generate-ddl: false
        # hibernate entry to
#        hibernate:
#          ddl-auto: update
#          naming:
#            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
###            physical-strategy: org.hibernate.boot.model.naming.SpringPhysicalNamingStrategy
###            physical_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
###            implicit_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        # spring entry one
        properties:
          aaaa: 11111111111
          hibernate:
#            hbm2ddl:
#              auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect
            #dialect: org.hibernate.dialect.MySQL57Dialect
            physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#            implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy



#  rabbitmq:
#    main:
#      host: mecs.com
#      port: 5672
#      username: admin
#      password: admin
#      virtual-host: /
#      binding-list:
#        - type: direct
#          routing-key: application-log-queue
#          queue: application-log-queue
#          exchange: application-log-exchange
#
#  redis:
#    host: 192.168.155.150
#    port: 6379
#    password: YYYYYYYY

  log:
#    enabled: false
#    async: false
#    samplerRate: 0.5
#    level: debug
    rabbitmq:
      enabled: false
      host: mecs.com
      port: 5672
      username: admin
      password: admin
      virtual-host: /
      es-index: @project.deploy.finalName@-@profiles.active@-log
      publisher-confirms: true
      publisher-returns: true
      auto-declare: true
      binding-list:
      - type: direct
        routing-key: application-log-queue
        queue: application-log-queue
        exchange: application-log-exchange

    kafka:
      enabled: false
      esIndex: @project.deploy.finalName@-@profiles.active@-log
      bootstrap-servers: 192.168.0.133:9092
#      template:
#        defaultTopic: application-log
#      producer:
#        bootstrap-servers: mecs.com:9092
#        bootstrap-servers: 192.168.133.133:9092
      binding-list:
        - topic: application-log
      properties:
        linger-ms: 100
        max-block-ms: 3000
        request-timeout-ms: 1000
        transaction-timeout-ms: 1000
        compression-type: gzip
        acks: 1
    console:
      enabled: false
    slf4j:
      enabled: true

#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: ${spring.cloud.client.ipAddress}:${server.port}
#    lease-expiration-duration-in-seconds: 60        # default value
#    lease-renewal-interval-in-seconds: 30           # default value
#  client:
#    service-url:
#      defaultZone: http://192.168.155.105:7777/eureka, http://192.168.155.105:8888/eureka, http://192.168.155.105:9999/eureka
#    register-with-eureka: true

#  redis:
#    host: mecs.com
#    port: 6379
#    timeout: 10
#    password: YYYYYYYY


server:
  tomcat:
    max-connections: 999


org:
  springframework:
    boot:
      logging:
        LoggingSystem: 1111

mybatis-plus:
  configuration:
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

swagger:
  enabled: true
