spring:
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mecs.com:3306/tdatabase?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&useCursorFetch=true
      username: root
      password: 1111
      mybatis:
        mapper-locations: classpath:config/mapper/*.xml

    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mecs.com:3306/tdatabase?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&useCursorFetch=true
      username: root
      password: 1111
      mybatis:
        mapper-locations: classpath:config/mapper/*.xml

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mecs.com:3306/tdatabase?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true&useCursorFetch=true
    username: root
    password: 1111

    third:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mecs.com:3306/tdatabase?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true&useCursorFetch=true
      username: root
      password: 1111
      jpa:
        database: mysql
        #启动时需要初始化的建表语句
        schema: classpath:schema-mysql.sql
        #初始化的数据
        data: classpath:data-mysql.sql
        show-sql: true
        open-in-view: false
        generate-ddl: true
        # hibernate entry to
#        hibernate:
#          ddl-auto: update
#          naming:
#    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    #        physical-strategy: org.hibernate.boot.model.naming.SpringPhysicalNamingStrategy
#            physical_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    #        implicit_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        # spring entry one
        properties:
          hibernate:
            hbm2ddl:
              auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect
            #            dialect: org.hibernate.dialect.MySQL57Dialect
            physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  #            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



#  rabbitmq:
#    main:
#      host: mecs.com
#      port: 5672
#      username: admin
#      password: admin
#      virtual-host: /
#      binding-list:
#        - type: direct
#          routing-key: application-log-queue
#          queue: application-log-queue
#          exchange: application-log-exchange
#
#  redis:
#    host: 192.168.155.150
#    port: 6379
#    password: Yixin4redis

  log:
    rabbitmq:
      enable: true
      host: mecs.com
#      host: 10.124.163.95
      port: 5672
      username: admin
      password: 1
      virtual-host: /
      es-index: @project.deploy.finalName@-@profiles.active@-log
      publisher-confirms: true
      publisher-returns: true
      binding-list:
      - type: direct
        routing-key: application-log-queue
        queue: application-log-queue
        exchange: application-log-exchange
#
#    kafka:
#      enable: false
#      esIndex: @project.build.finalName@-@profiles.active@-log
#      topic: basic_application_log
#      template:
#        defaultTopic: basic_application_log
#      producer:
#        bootstrap-servers: 192.168.177.211:9092
#      properties:
#        linger-ms: 100
#        max-block-ms: 3000
#        request-timeout-ms: 1000
#        transaction-timeout-ms: 1000
#        compression-type: gzip
#        acks: 1


#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: ${spring.cloud.client.ipAddress}:${server.port}
#    lease-expiration-duration-in-seconds: 60        # default value
#    lease-renewal-interval-in-seconds: 30           # default value
#  client:
#    service-url:
#      defaultZone: http://192.168.155.105:7777/eureka, http://192.168.155.105:8888/eureka, http://192.168.155.105:9999/eureka
#    register-with-eureka: true


