-- DROP TABLE IF EXISTS user;
--
-- CREATE TABLE user
-- (
-- 	id BIGINT(20) NOT NULL COMMENT '主键ID',
-- 	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
-- 	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
-- 	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
-- 	PRIMARY KEY (id)
-- );


-- CREATE SCHEMA IF NOT EXISTS `tdatabase` DEFAULT CHARACTER SET utf8 ;
-- USE `tdatabase`;

-- DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);

-- DROP TABLE IF EXISTS book;
CREATE TABLE IF NOT EXISTS book
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    name VARCHAR(50) NULL DEFAULT NULL COMMENT '姓名',
    author VARCHAR(30) NULL DEFAULT NULL COMMENT '作者',
    description VARCHAR(500) NULL DEFAULT NULL COMMENT '描述',
    PRIMARY KEY (id)
);
